CUDA_INDEX:     2


VHS_COEFF:      5.0
VHS_EXPONENT:   -3.0
INIT_TYPE:      'bimaxwellian'


PATH_D:         'pretrained_operators/op_D__FPL2D__gamma-3.0__res064__seed0.pth'
PATH_F:         'pretrained_operators/op_F__FPL2D__gamma-3.0__res064__seed0.pth'